/**
 * Builds test/fixtures/<dir>/manifest.json.
 *
 * Expectations come from libheif's `heif-info` and from `exiftool`, never from
 * our own parser — a manifest generated by the code under test asserts nothing.
 *
 * Usage: node --experimental-strip-types tools/make-manifest.ts test/fixtures/local
 */
import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync } from 'node:fs';
import { extname, join } from 'node:path';

const dir = process.argv[2];
if (!dir) {
  console.error('usage: make-manifest.ts <fixtures-dir>');
  process.exit(2);
}

const manifest: Record<string, unknown> = {};

for (const name of readdirSync(dir).sort()) {
  if (!['.heic', '.heif'].includes(extname(name).toLowerCase())) continue;
  const path = join(dir, name);

  const info = execFileSync('heif-info', [path], { encoding: 'utf8' });
  const primary = /image: (\d+)x(\d+) \(id=\d+\), primary/.exec(info);
  if (!primary) {
    console.error(`  skipping ${name}: heif-info reported no primary image`);
    continue;
  }
  const tiles = /tiles: (\d+)x(\d+), tile size: (\d+)x(\d+)/.exec(info);
  const depth = /bit depth: (\d+)/.exec(info);
  const angle = /angle \(ccw\): (\d+)/.exec(info);
  const mirror = /mirror: (horizontal|vertical)/.exec(info);
  const brand = /main brand: (\w+)/.exec(info);
  const hasAlpha = /alpha channel: yes/.test(info);
  const hasDepth = /depth channel: yes/.test(info);
  const gainMap = /hdrgainmap/i.test(info);

  const model = safe(() => execFileSync('exiftool', ['-s3', '-Model', path], { encoding: 'utf8' }).trim());
  const software = safe(() => execFileSync('exiftool', ['-s3', '-Software', path], { encoding: 'utf8' }).trim());

  const rotation = angle ? Number(angle[1]) : 0;
  // heif-info reports display dimensions and the display tile layout, so a
  // 90/270 rotation swaps both relative to the coded image.
  const rotated = rotation === 90 || rotation === 270;

  manifest[name] = {
    device: model || 'unknown',
    software: software || undefined,
    brand: brand?.[1],
    expect: {
      // As displayed, i.e. after container transforms.
      width: Number(primary[1]),
      height: Number(primary[2]),
      isGrid: tiles !== null,
      tileCount: tiles ? Number(tiles[1]) * Number(tiles[2]) : 1,
      gridColumns: tiles ? Number(rotated ? tiles[2] : tiles[1]) : 1,
      gridRows: tiles ? Number(rotated ? tiles[1] : tiles[2]) : 1,
      bitDepth: depth ? Number(depth[1]) : 8,
      rotation,
      mirrored: mirror ? mirror[1] : 'none',
    },
    features: {
      alpha: hasAlpha || undefined,
      depth: hasDepth || undefined,
      gainMap: gainMap || undefined,
    },
    reference: `${name.replace(/\.[^.]+$/, '')}.ref.png`,
  };
  console.error(`  ${name}: ${primary[1]}x${primary[2]} ${tiles ? `grid ${tiles[1]}x${tiles[2]}` : 'single'} d${depth?.[1] ?? 8} r${rotation}`);
}

const out = join(dir, 'manifest.json');
writeFileSync(out, `${JSON.stringify(manifest, null, 2)}\n`);
console.error(`\nwrote ${out} (${Object.keys(manifest).length} fixtures)`);

function safe(fn: () => string): string {
  try {
    return fn();
  } catch {
    return '';
  }
}
